In [1]:
import pandas as pd
import numpy as np
from fredapi import Fred
fred = Fred(api_key='c2142066cce2050ddf167730db63188d')

In [2]:
#data['date'] = data['date'].apply(lambda x: str(x)[0:10])
#data['realtime_start'] = data['realtime_start'].apply(lambda x: str(x)[0:10])
#data.tail()

#data = fred.get_series_all_releases('dgs10')
#data['diff'] = data['realtime_start'] - data['date']
#data['date'] = data['date'].apply(lambda x: str(x)[0:10])
#data['realtime_start'] = data['realtime_start'].apply(lambda x: str(x)[0:10])
#data['diff'] = data['diff'].apply(lambda x: x.days)

In [3]:
table = pd.DataFrame({'date':pd.date_range('1970-01-01','2018-03-17')})
table['date'] = table['date'].apply(lambda x: str(x)[0:10])
#table = table.set_index('date')

#restricts each reporting period to the original report date, ignoring revisions
def add_first(dt, st, v, sym):
    global df
    if(len(df[df[sym+'_dt'].str.contains(dt)]) == 0 &
        abs((pd.to_datetime(dt) - pd.to_datetime(st)).days) < 300):
        tmp = pd.DataFrame({sym+'_dt':[dt], 'date':[st], sym:[v]})
        df = df.append(tmp, ignore_index=True)

#ignores historical data that is dumped all on the same day when the survey first becomes active
def add_indicator(sym):
    global table
    global df
    data = fred.get_series_all_releases(sym)
    data['diff'] = data['realtime_start'] - data['date']
    data['diff'] = data['diff'].apply(lambda x: x.days)
    data['date'] = data['date'].apply(lambda x: str(x)[0:10])
    data['realtime_start'] = data['realtime_start'].apply(lambda x: str(x)[0:10])
    if(sym not in ['VIXCLS','DGS10']):
        diff = 60
    else:
        diff = 2
    data = data[data['diff'] < diff]
    
    df = pd.DataFrame(columns=[sym+'_dt','date',sym])
    [add_first(row[1],row[2],row[3],sym) for row in data.itertuples()]
    #table = table.join(df.set_index('realtime_start'))
    table = table.merge(df,on='date',how='left')

In [4]:
symbols = ['AHETPI','CEU2000000001','HOUST','UNRATENSA','EMRATIO','UEMPMED','CPIAUCSL','UMCSENT','SPCS20RNSA','KCFSI','VIXCLS','DGS10']

[add_indicator(sym) for sym in symbols]

[None, None, None, None, None, None, None, None, None, None, None, None]

In [5]:
table.fillna(method='ffill',inplace=True)
table

,date,AHETPI,AHETPI_dt,CEU2000000001,CEU2000000001_dt,HOUST,HOUST_dt,UNRATENSA,UNRATENSA_dt,EMRATIO,...,UMCSENT,UMCSENT_dt,SPCS20RNSA_dt,SPCS20RNSA,KCFSI,KCFSI_dt,VIXCLS,VIXCLS_dt,DGS10,DGS10_dt
0,1970-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1970-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1970-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1970-01-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1970-01-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1970-01-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,1970-01-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1970-01-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,1970-01-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1970-01-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,1970-01-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,1970-01-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,1970-01-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,1970-01-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,1970-01-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,1970-01-16,NaN,NaN,NaN,NaN,1245.0,1969-12-01,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,1970-01-17,NaN,NaN,NaN,NaN,1245.0,1969-12-01,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,1970-01-18,NaN,NaN,NaN,NaN,1245.0,1969-12-01,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,1970-01-19,NaN,NaN,NaN,NaN,1245.0,1969-12-01,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,1970-01-20,NaN,NaN,NaN,NaN,1245.0,1969-12-01,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,1970-01-21,NaN,NaN,NaN,NaN,1245.0,1969-12-01,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,1970-01-22,NaN,NaN,NaN,NaN,1245.0,1969-12-01,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,1970-01-23,NaN,NaN,NaN,NaN,1245.0,1969-12-01,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,1970-01-24,NaN,NaN,NaN,NaN,1245.0,1969-12-01,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,1970-01-25,NaN,NaN,NaN,NaN,1245.0,1969-12-01,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,1970-01-26,NaN,NaN,NaN,NaN,1245.0,1969-12-01,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,1970-01-27,NaN,NaN,NaN,NaN,1245.0,1969-12-01,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,1970-01-28,NaN,NaN,NaN,NaN,1245.0,1969-12-01,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,1970-01-29,NaN,NaN,NaN,NaN,1245.0,1969-12-01,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,1970-01-30,NaN,NaN,NaN,NaN,1245.0,1969-12-01,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17619,2018-02-17,22.34,2018-01-01,6692.0,2018-01-01,1326.0,2018-01-01,4.5,2018-01-01,60.1,...,99.7,2018-02-01,NaN,NaN,-0.82,2018-01-01,19.46,2018-02-16,2.90,2018-02-15
17620,2018-02-18,22.34,2018-01-01,6692.0,2018-01-01,1326.0,2018-01-01,4.5,2018-01-01,60.1,...,99.7,2018-02-01,NaN,NaN,-0.82,2018-01-01,19.46,2018-02-16,2.90,2018-02-15
17621,2018-02-19,22.34,2018-01-01,6692.0,2018-01-01,1326.0,2018-01-01,4.5,2018-01-01,60.1,...,99.7,2018-02-01,NaN,NaN,-0.82,2018-01-01,19.46,2018-02-16,2.90,2018-02-15
17622,2018-02-20,22.34,2018-01-01,6692.0,2018-01-01,1326.0,2018-01-01,4.5,2018-01-01,60.1,...,99.7,2018-02-01,NaN,NaN,-0.82,2018-01-01,19.46,2018-02-19,2.90,2018-02-15
17623,2018-02-20,22.34,2018-01-01,6692.0,2018-01-01,1326.0,2018-01-01,4.5,2018-01-01,60.1,...,99.7,2018-02-01,NaN,NaN,-0.82,2018-01-01,20.60,2018-02-20,2.90,2018-02-15
17624,2018-02-21,22.34,2018-01-01,6692.0,2018-01-01,1326.0,2018-01-01,4.5,2018-01-01,60.1,...,99.7,2018-02-01,NaN,NaN,-0.82,2018-01-01,20.02,2018-02-21,2.88,2018-02-20
17625,2018-02-22,22.34,2018-01-01,6692.0,2018-01-01,1326.0,2018-01-01,4.5,2018-01-01,60.1,...,99.7,2018-02-01,NaN,NaN,-0.82,2018-01-01,18.72,2018-02-22,2.94,2018-02-21
17626,2018-02-23,22.34,2018-01-01,6692.0,2018-01-01,1326.0,2018-01-01,4.5,2018-01-01,60.1,...,99.7,2018-02-01,NaN,NaN,-0.82,2018-01-01,16.49,2018-02-23,2.92,2018-02-22
17627,2018-02-24,22.34,2018-01-01,6692.0,2018-01-01,1326.0,2018-01-01,4.5,2018-01-01,60.1,...,99.7,2018-02-01,NaN,NaN,-0.82,2018-01-01,16.49,2018-02-23,2.92,2018-02-22
17628,2018-02-25,22.34,2018-01-01,6692.0,2018-01-01,1326.0,2018-01-01,4.5,2018-01-01,60.1,...,99.7,2018-02-01,NaN,NaN,-0.82,2018-01-01,16.49,2018-02-23,2.92,2018-02-22
17629,2018-02-26,22.34,2018-01-01,6692.0,2018-01-01,1326.0,2018-01-01,4.5,2018-01-01,60.1,...,99.7,2018-02-01,NaN,NaN,-0.82,2018-01-01,15.80,2018-02-26,2.92,2018-02-22
17630,2018-02-27,22.34,2018-01-01,6692.0,2018-01-01,1326.0,2018-01-01,4.5,2018-01-01,60.1,...,99.7,2018-02-01,NaN,NaN,-0.82,2018-01-01,18.59,2018-02-27,2.86,2018-02-26
17631,2018-02-28,22.34,2018-01-01,6692.0,2018-01-01,1326.0,2018-01-01,4.5,2018-01-01,60.1,...,99.7,2018-02-01,NaN,NaN,-0.82,2018-01-01,19.85,2018-02-28,2.90,2018-02-27
17632,2018-03-01,22.34,2018-01-01,6692.0,2018-01-01,1326.0,2018-01-01,4.5,2018-01-01,60.1,...,99.7,2018-02-01,NaN,NaN,-0.82,2018-01-01,22.47,2018-03-01,2.87,2018-02-28
17633,2018-03-02,22.34,2018-01-01,6692.0,2018-01-01,1326.0,2018-01-01,4.5,2018-01-01,60.1,...,99.7,2018-02-01,NaN,NaN,-0.82,2018-01-01,19.59,2018-03-02,2.87,2018-02-28
17634,2018-03-03,22.34,2018-01-01,6692.0,2018-01-01,1326.0,2018-01-01,4.5,2018-01-01,60.1,...,99.7,2018-02-01,NaN,NaN,-0.82,2018-01-01,19.59,2018-03-02,2.87,2018-02-28
17635,2018-03-04,22.34,2018-01-01,6692.0,2018-01-01,1326.0,2018-01-01,4.5,2018-01-01,60.1,...,99.7,2018-02-01,NaN,NaN,-0.82,2018-01-01,19.59,2018-03-02,2.87,2018-02-28
17636,2018-03-05,22.34,2018-01-01,6692.0,2018-01-01,1326.0,2018-01-01,4.5,2018-01-01,60.1,...,99.7,2018-02-01,NaN,NaN,-0.82,2018-01-01,18.73,2018-03-05,2.87,2018-02-28
17637,2018-03-06,22.34,2018-01-01,6692.0,2018-01-01,1326.0,2018-01-01,4.5,2018-01-01,60.1,...,99.7,2018-02-01,NaN,NaN,-0.82,2018-01-01,18.36,2018-03-06,2.88,2018-03-05
17638,2018-03-07,22.34,2018-01-01,6692.0,2018-01-01,1326.0,2018-01-01,4.5,2018-01-01,60.1,...,99.7,2018-02-01,NaN,NaN,-0.82,2018-01-01,17.76,2018-03-07,2.88,2018-03-06
17639,2018-03-08,22.34,2018-01-01,6692.0,2018-01-01,1326.0,2018-01-01,4.5,2018-01-01,60.1,...,99.7,2018-02-01,NaN,NaN,-0.44,2018-02-01,16.54,2018-03-08,2.89,2018-03-07
17640,2018-03-09,22.40,2018-02-01,6800.0,2018-02-01,1326.0,2018-01-01,4.4,2018-02-01,60.4,...,99.7,2018-02-01,NaN,NaN,-0.44,2018-02-01,14.64,2018-03-09,2.86,2018-03-08
17641,2018-03-10,22.40,2018-02-01,6800.0,2018-02-01,1326.0,2018-01-01,4.4,2018-02-01,60.4,...,99.7,2018-02-01,NaN,NaN,-0.44,2018-02-01,14.64,2018-03-09,2.86,2018-03-08
17642,2018-03-11,22.40,2018-02-01,6800.0,2018-02-01,1326.0,2018-01-01,4.4,2018-02-01,60.4,...,99.7,2018-02-01,NaN,NaN,-0.44,2018-02-01,14.64,2018-03-09,2.86,2018-03-08
17643,2018-03-12,22.40,2018-02-01,6800.0,2018-02-01,1326.0,2018-01-01,4.4,2018-02-01,60.4,...,99.7,2018-02-01,NaN,NaN,-0.44,2018-02-01,15.78,2018-03-12,2.86,2018-03-08
17644,2018-03-13,22.40,2018-02-01,6800.0,2018-02-01,1326.0,2018-01-01,4.4,2018-02-01,60.4,...,99.7,2018-02-01,NaN,NaN,-0.44,2018-02-01,16.35,2018-03-13,2.87,2018-03-12
17645,2018-03-14,22.40,2018-02-01,6800.0,2018-02-01,1326.0,2018-01-01,4.4,2018-02-01,60.4,...,99.7,2018-02-01,NaN,NaN,-0.44,2018-02-01,17.23,2018-03-14,2.84,2018-03-13
17646,2018-03-15,22.40,2018-02-01,6800.0,2018-02-01,1326.0,2018-01-01,4.4,2018-02-01,60.4,...,99.7,2018-02-01,NaN,NaN,-0.44,2018-02-01,16.59,2018-03-15,2.81,2018-03-14
17647,2018-03-16,22.40,2018-02-01,6800.0,2018-02-01,1236.0,2018-02-01,4.4,2018-02-01,60.4,...,99.7,2018-02-01,NaN,NaN,-0.44,2018-02-01,16.59,2018-03-15,2.82,2018-03-15
17648,2018-03-17,22.40,2018-02-01,6800.0,2018-02-01,1236.0,2018-02-01,4.4,2018-02-01,60.4,...,99.7,2018-02-01,NaN,NaN,-0.44,2018-02-01,16.59,2018-03-15,2.82,2018-03-15

In [6]:
table.to_csv('indicators.csv')